FROM oven/bun:1 AS base
WORKDIR /usr/src/app

FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lock /temp/dev/
COPY packages /temp/dev/packages/
COPY apps/serve/package.json /temp/dev/apps/serve/
RUN cd /temp/dev && bun install

RUN mkdir -p /temp/prod
COPY package.json bun.lock /temp/prod/
COPY packages /temp/prod/packages/
COPY apps/serve/package.json /temp/prod/apps/serve/
RUN cd /temp/prod && bun install

FROM base AS prerelease
COPY --from=install /temp/dev/package.json .
COPY --from=install /temp/dev/bun.lock .
COPY --from=install /temp/dev/node_modules node_modules
COPY --from=install /temp/dev/packages ./packages/
COPY --from=install /temp/dev/apps ./apps
RUN bun install

ENV NODE_ENV=production
RUN cd apps/serve && bun run compile

FROM base AS release
COPY --from=install /temp/prod/node_modules node_modules
COPY --from=prerelease /usr/src/app/packages ./packages/
COPY --from=prerelease /usr/src/app/apps ./apps
COPY --from=prerelease /usr/src/app/package.json .

RUN cd apps/serve && bun run compile

RUN rm -rf apps/*/src apps/*/*.map packages/*/src packages/*/*.map *.map

USER bun
EXPOSE 5173/tcp
ENTRYPOINT [ "bun", "run", "index.js" ]