 export const TOPIC = {
    PRIME_TO_ORCHESTRATOR: "PRIME_TO_ORCHESTRATOR",
    ORCHESTRATOR_TO_CONTROL: "ORCHESTRATOR_TO_CONTROL",
    BETWEEN_PODS: "BETWEEN_PODS",
    SERVING_TO_ORCHESTRATOR: "SERVING_TO_ORCHESTRATOR",
    ORCHESTRATOR_TO_PRIME: "ORCHESTRATOR_TO_PRIME",
    PROJECT_CREATED: "PROJECT_CREATED",
    PROJECT_INITIALIZED: "PROJECT_INITIALIZED",
}

export const GROUP_ID = {
    SERVING_POD: "SERVING_POD",
    CONTROL_POD: "CONTROL_POD",
    BETWEEN_PODS: "BETWEEN_PODS",
}