export const TOPIC = {
  PRIME_TO_ORCHESTRATOR: "PRIME_TO_ORCHESTRATOR",
  ORCHESTRATOR_TO_CONTROL: "ORCHESTRATOR_TO_CONTROL",
  ORCHESTRATOR_TO_SERVING: "ORCHESTRATOR_TO_SERVING",
  SERVING_TO_ORCHESTRATOR: "SERVING_TO_ORCHESTRATOR",
  ORCHESTRATOR_TO_PRIME: "ORCHESTRATOR_TO_PRIME",
  CONTROL_TO_SERVING: "CONTROL_TO_SERVING",
  SERVING_TO_CONTROL: "SERVING_TO_CONTROL",
  CONTROL_TO_ORCHESTRATOR: "CONTROL_TO_ORCHESTRATOR",
};

export const GROUP_ID = {
  SERVING_POD: "SERVING_POD",
  CONTROL_POD: "CONTROL_POD",
  SERVING_TO_CONTROL: "SERVING_TO_CONTROL",
  CONTROL_TO_SERVING: "CONTROL_TO_SERVING",
};

export const MESSAGE_KEYS = {
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_INITIALIZED: "PROJECT_INITIALIZED",
  SERVING_PROJECT_INITIALIZED: "SERVING_PROJECT_INITIALIZED",
  SERVING_PROJECT_INITIALIZATION_CONFIRMED:
    "SERVING_PROJECT_INITIALIZATION_CONFIRMED",
  PROJECT_BUILD: "PROJECT_BUILD",
  PROJECT_RUN: "PROJECT_RUN",
  PROJECT_FAILED: "PROJECT_FAILED",
  PROMPT_RESPONSE: "PROMPT_RESPONSE",
};
