package types

import "github.com/segmentio/kafka-go"

type KafkaClient struct {
	Reader *kafka.Reader
	Writer *kafka.Writer
}

type PubSubIncomingMessage struct {
	Topic   string
	Message []byte
}

// topic

const (
	PROJECT_TOPIC           = "PROJECT_TOPIC"
	PROJECT_RESPONSE_TOPIC  = "PROJECT_RESPONSE_TOPIC"
	ORCHESTRATOR_TO_CONTROL = "ORCHESTRATOR_TO_CONTROL"
	CONTROL_TO_ORCHESTRATOR = "CONTROL_TO_ORCHESTRATOR"
	CONTROL_TO_SERVING      = "CONTROL_TO_SERVING"
	SERVING_TO_CONTROL      = "SERVING_TO_CONTROL"
	SERVING_TO_ORCHESTRATOR = "SERVING_TO_ORCHESTRATOR"
	ORCHESTRATOR_TO_SERVING = "ORCHESTRATOR_TO_SERVING"
	POD_TOPIC               = "POD_TOPIC"
)

// gourpId

const (
	PROJECT_GROUP_ID          = "PROJECT_GROUP_ID"
	PROJECT_RESPONSE_GROUP_ID = "PROJECT_RESPONSE_GROUP_ID"
	ORCHESTRATOR_GROUP_ID     = "ORCHESTRATOR_GROUP_ID"
	CONTROL_GROUP_ID          = "CONTROL_GROUP_ID"
	SERVING_GROUP_ID          = "SERVING_GROUP_ID"
	POD_GROUP_ID              = "POD_GROUP_ID"
)
