apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orchestrator-role
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrator-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: orchestrator
    namespace: default
roleRef:
  kind: Role
  name: orchestrator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      serviceAccountName: orchestrator
      containers:
         - name: orchestrator
           image: aivalacoder/elbavol-orchestrator:latest
           imagePullPolicy: Never
           ports:
             - containerPort: 8080
           env:
             - name: KAFKA_URL
               value: "kafka.default.svc.cluster.local:9092" # docker : "host.docker.internal:9092"
             - name: DOCKER_USER_NAME
               value: "aivalacoder"
             - name: GOOGLE_API_KEY
               value: ""
             - name: OPENROUTER_API_KEY
               value: ""
             - name: MINIO_ENDPOINT
               value: "http://minio.default.svc.cluster.local:9000" # docker : "http://host.docker.internal:9000" 
             - name: MINIO_ACCESS_KEY
               value: "minioadmin"
             - name: MINIO_SECRET_KEY
               value: "minioadmin"
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: default
spec:
  selector:
    app: orchestrator
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
