apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prime
  template:
    metadata:
      labels:
        app: prime
    spec:
       containers:
         - name: prime
           image: aivalacoder/elbavol-prime:latest
           imagePullPolicy: Never
           ports:
             - containerPort: 8080
           env:
             - name: KAFKA_URL
               value: "host.docker.internal:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: prime
  namespace: default
spec:
  selector:
    app: prime
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
