apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: default
type: Opaque
stringData:
  accessKey: "minioadmin"
  secretKey: "minioadmin"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
  namespace: default
type: Opaque
stringData:
  googleApiKey: ""
  openrouterApiKey: ""
